name: Pro-Build Multi-Platform-Folders

on:
  push:
    branches:
      - main
    paths:
      - 'run-build/**'
      - 'ESP32-Classic/**'
      - 'ESP32-C3/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      fail-fast: false  # TAMBAHKAN INI: Agar C3 tetap lanjut walau Classic error
      matrix:
        board: [
          {name: "ESP32-Classic", fqbn: "esp32:esp32:esp32", core: "2.0.17", dir: "ESP32-Classic"},
          {name: "ESP32-C3", fqbn: "esp32:esp32:esp32c3", core: "3.0.7", dir: "ESP32-C3"}
        ]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Get Timestamp
        id: timestamp
        run: echo "time=$(date +'%Y%m%d-%H%M')" >> $GITHUB_OUTPUT

      - name: Setup Arduino CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
          sudo mv bin/arduino-cli /usr/local/bin/
          arduino-cli config init
          arduino-cli config add board_manager.additional_urls https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json

      - name: Install Core
        run: |
          arduino-cli core update-index
          arduino-cli core install esp32:esp32@${{ matrix.board.core }}

      - name: Compile
        run: |
          mkdir -p ./build/${{ matrix.board.name }}
          # Kompilasi dari folder spesifik sesuai matrix
          arduino-cli compile --fqbn ${{ matrix.board.fqbn }} --output-dir ./build/${{ matrix.board.name }} ./${{ matrix.board.dir }}

      - name: Prepare Release Files
        run: |
          mkdir -p ./dist
          TS="${{ steps.timestamp.outputs.time }}"
          # Ambil file OTA dan ZIP sesuai folder board
          cp ./build/${{ matrix.board.name }}/*.ino.bin ./dist/${{ matrix.board.name }}-OTA-$TS.bin
          cd ./build/${{ matrix.board.name }}
          zip -r ../../dist/${{ matrix.board.name }}-FullFlash-$TS.zip .
          
      - name: Release to GitHub
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "Build-${{ steps.timestamp.outputs.time }}"
          name: "Release ${{ steps.timestamp.outputs.time }}"
          files: |
            dist/*.bin
            dist/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
