name: Build ESP32 Firmware

on: [push, workflow_dispatch] # Berjalan otomatis saat update kode atau manual

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Arduino CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
          sudo mv bin/arduino-cli /usr/local/bin/

      - name: Install ESP32 Core
        run: |
          arduino-cli core update-index
          arduino-cli core install esp32:esp32

      - name: Compile for ESP32-C3
        run: |
          arduino-cli compile --fqbn esp32:esp32:esp32c3 --output-dir ./build/c3 .

      - name: Compile for ESP32-S3
        run: |
          arduino-cli compile --fqbn esp32:esp32:esp32s3 --output-dir ./build/s3 .

      - name: Upload Binaries
        uses: actions/upload-artifact@v3
        with:
          name: esp32-firmware
          path: ./build/
          
