name: Pro-Build Multi-Platform

on:
  push:
    branches:
      - main
    paths:
      - 'run-build/**'
      - '**.ino'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        board: [
          {name: "ESP32-Classic", fqbn: "esp32:esp32:esp32", core: "2.0.17"},
          {name: "ESP32-C3", fqbn: "esp32:esp32:esp32c3", core: "3.0.7"}
        ]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Arduino CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
          sudo mv bin/arduino-cli /usr/local/bin/
          arduino-cli config init
          arduino-cli config add board_manager.additional_urls https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json

      - name: Install Core
        run: |
          arduino-cli core update-index
          arduino-cli core install esp32:esp32@${{ matrix.board.core }}

      - name: Compile
        run: |
          mkdir -p ./build/${{ matrix.board.name }}
          # Compile dan hasilkan semua file bin (bootloader, partitions, app)
          arduino-cli compile --fqbn ${{ matrix.board.fqbn }} --output-dir ./build/${{ matrix.board.name }} .

      - name: Prepare Release Files
        run: |
          mkdir -p ./dist
          
          # 1. Ambil file .bin utama untuk keperluan OTA
          cp ./build/${{ matrix.board.name }}/*.ino.bin ./dist/${{ matrix.board.name }}-OTA.bin
          
          # 2. Buat ZIP Bundle Lengkap untuk Flashing lewat Kabel di Android
          cd ./build/${{ matrix.board.name }}
          zip -r ../../dist/${{ matrix.board.name }}-FullFlash-Bundle.zip .
          
      - name: Release to GitHub
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          files: |
            dist/*.bin
            dist/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
